name: Lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './codex_remote'
      - name: Run static tests
        run: bash codex_remote/tests/test_static.sh
      - uses: frenck/action-addon-linter@v2.21.0
        with:
          path: ./codex_remote
